spring:
  mail:
    host: smtp.163.com
    username: 123@163.com
    #需要使用发送邮件服务的 授权码， 并开启IMAP/SMTP服务
    password: 00000000
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: 00000000
      expire: 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      auth:
  datasource:
    username: 000000
    password: 000000
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.cj.jdbc.Driver
